src/Entity/DataBc.php
<?php

namespace App\Entity;

use App\Repository\DataBcRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=DataBcRepository::class)
 */
class DataBc
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", columnDefinition="enum('homme', 'femme')")
     */
    private $sexe;

    /**
     * @ORM\Column(type="decimal", precision=3, scale=2)
     */
    private $height;

    /**
     * @ORM\Column(type="integer")
     */
    private $weight;

    /**
     * @ORM\Column(type="date")
     */
    public $calculate_date;

    /**
     * @ORM\Column(type="string", columnDefinition="enum('inactif', 'légèrement actif', 'actif', 'très actif')")
     */
    public $activity;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $bc;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="dataBcs")
     */
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSexe(): ?string
    {
        return $this->sexe;
    }

    public function setSexe(string $sexe): self
    {
        $this->sexe = $sexe;

        return $this;
    }

    public function getHeight(): ?float
    {
        return $this->height;
    }

    public function setHeight(float $height): self
    {
        $this->height = $height;

        return $this;
    }

    public function getWeight(): ?int
    {
        return $this->weight;
    }

    public function setWeight(int $weight): self
    {
        $this->weight = $weight;

        return $this;
    }

    public function getCalculateDate(): ?\DateTimeInterface
    {
        return $this->calculate_date;
    }

    public function setCalculateDate(\DateTimeInterface $calculate_date): self
    {
        $this->calculate_date = $calculate_date;

        return $this;
    }

    public function getActivity(): ?string
    {
        return $this->activity;
    }

    public function setActivity(string $activity): self
    {
        $this->activity = $activity;

        return $this;
    }

    public function getBc(): ?string
    {
        return $this->bc;
    }

    public function setBc(string $bc): self
    {
        $this->bc = $bc;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Form/DataBcType.php
<?php

namespace App\Form;

use App\Entity\DataBc;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DataBcType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('sexe', ChoiceType::class,['choices' => ['Homme'=>'homme','Femme'=>"femme"]])
            ->add('height')
            ->add('weight')
            // ->add('calculate_date')
            ->add('activity', ChoiceType::class,['choices' => [
                'Inactif'=>"inactif",
                'Légèrement Actif'=>"légèrement actif",
                'Actif'=>"actif",
                'Très Actif'=>"très actif"]])
            // ->add('bc')
            // ->add('user')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => DataBc::class,
        ]);
    }
}

src/Controller/DataBcController.php
<?php

namespace App\Controller;

use App\Entity\DataBc;
use App\Form\DataBcType;
use App\Repository\DataBcRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/data/bc")
 */
class DataBcController extends AbstractController
{
    /**
     * @Route("/", name="app_data_bc_index", methods={"GET"})
     */
    public function index(DataBcRepository $dataBcRepository): Response
    {
        return $this->render('data_bc/index.html.twig', [
            'data_bcs' => $dataBcRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_data_bc_new", methods={"GET", "POST"})
     */
    public function new(Request $request, DataBcRepository $dataBcRepository): Response
    {
        $dataBc = new DataBc();
        $form = $this->createForm(DataBcType::class, $dataBc);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $dataBcRepository->add($dataBc, true);

            return $this->redirectToRoute('app_data_bc_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('data_bc/new.html.twig', [
            'data_bc' => $dataBc,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_data_bc_show", methods={"GET"})
     */
    public function show(DataBc $dataBc): Response
    {
        return $this->render('data_bc/show.html.twig', [
            'data_bc' => $dataBc,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_data_bc_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, DataBc $dataBc, DataBcRepository $dataBcRepository): Response
    {
        $form = $this->createForm(DataBcType::class, $dataBc);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $dataBcRepository->add($dataBc, true);

            return $this->redirectToRoute('app_data_bc_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('data_bc/edit.html.twig', [
            'data_bc' => $dataBc,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_data_bc_delete", methods={"POST"})
     */
    public function delete(Request $request, DataBc $dataBc, DataBcRepository $dataBcRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$dataBc->getId(), $request->request->get('_token'))) {
            $dataBcRepository->remove($dataBc, true);
        }

        return $this->redirectToRoute('app_data_bc_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/data_bc/_delete_form.html.twig
<form method="post" action="{{ path('app_data_bc_delete', {'id': data_bc.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ data_bc.id) }}">
    <button class="btn">Delete</button>
</form>

templates/data_bc/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/data_bc/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit DataBc{% endblock %}

{% block body %}
    <h1>Edit DataBc</h1>

    {{ include('data_bc/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_data_bc_index') }}">back to list</a>

    {{ include('data_bc/_delete_form.html.twig') }}
{% endblock %}

templates/data_bc/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}DataBc index{% endblock %}

{% block body %}
    <h1>DataBc index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Sexe</th>
                <th>Height</th>
                <th>Weight</th>
                <th>Calculate_date</th>
                <th>Activity</th>
                <th>Bc</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for data_bc in data_bcs %}
            <tr>
                <td>{{ data_bc.id }}</td>
                <td>{{ data_bc.sexe }}</td>
                <td>{{ data_bc.height }}</td>
                <td>{{ data_bc.weight }}</td>
                <td>{{ data_bc.calculateDate ? data_bc.calculateDate|date('Y-m-d') : '' }}</td>
                <td>{{ data_bc.activity }}</td>
                <td>{{ data_bc.bc }}</td>
                <td>
                    <a href="{{ path('app_data_bc_show', {'id': data_bc.id}) }}">show</a>
                    <a href="{{ path('app_data_bc_edit', {'id': data_bc.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_data_bc_new') }}">Create new</a>
{% endblock %}

templates/data_bc/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New DataBc{% endblock %}

{% block body %}
    <h1>Create new DataBc</h1>

    {{ include('data_bc/_form.html.twig') }}

    <a href="{{ path('app_data_bc_index') }}">back to list</a>
{% endblock %}

templates/data_bc/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}DataBc{% endblock %}

{% block body %}
    <h1>DataBc</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ data_bc.id }}</td>
            </tr>
            <tr>
                <th>Sexe</th>
                <td>{{ data_bc.sexe }}</td>
            </tr>
            <tr>
                <th>Height</th>
                <td>{{ data_bc.height }}</td>
            </tr>
            <tr>
                <th>Weight</th>
                <td>{{ data_bc.weight }}</td>
            </tr>
            <tr>
                <th>Calculate_date</th>
                <td>{{ data_bc.calculateDate ? data_bc.calculateDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Activity</th>
                <td>{{ data_bc.activity }}</td>
            </tr>
            <tr>
                <th>Bc</th>
                <td>{{ data_bc.bc }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_data_bc_index') }}">back to list</a>

    <a href="{{ path('app_data_bc_edit', {'id': data_bc.id}) }}">edit</a>

    {{ include('data_bc/_delete_form.html.twig') }}
{% endblock %}